spring.application.name=app

# Port aplikacji
server.port=8080

# Ustawienia dla Oracle 21c XE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=przychodnia_user
spring.datasource.password=haslo123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Reszta bez zmian
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect